[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
[project]
name = "nnsight"
version = "0.0.6"
authors = [
  { name="Jaden Fiotto-Kaufman", email="jadenfk@outlook.com" },
]
description = "Package for interpreting and manipulating the internals of deep learning models."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "transformers",
    "protobuf",
    "python-socketio[client]",
    "tokenizers>=0.13.0",
    "pydantic>=2.4.0",
    "torch>=2.1.0",
    "sentencepiece>=0.16.0",
    "torchvision",
    "accelerate",
    "diffusers"
    ]
[project.urls]
"Homepage" = "https://github.com/JadenFiotto-Kaufman/nnsight"

[tool.setuptools]
include-package-data = true
[tool.setuptools.package-data]
nnsight = ["config.yaml", "nnsight.log"]

